server:
  port: 4000
eureka:
  client:
    service-url:      #配置当前微服务作为Eureka客户端来访问Eureka服务端时使用的地址
      defaultZone: http://localhost:5000/eureka/
spring:
  application:        #指定当前服务的名称，以便将来通过微服务的名称调用当前微服务时能够找到
    name: lbs-consumer